language: php

sudo: false

env:
  global:
  - secure: "cSujC/abhUMuBqgU88qrGg8fZPOfoXd6sCU+uD6HzAzt0JLNgxVwR0EHss8k7Vc4Z7Pp9FxQFq/f6ecjEbK8w5spw5Vmz8a0D2QE5CEb0vR4hElRqCxNmN+azAVIvB1zyomRtCEdYQTDbjx8K35Uarh4mykczr9oCidI0kc7Ae8="

matrix:
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
      env:
        - EXECUTE_AFTER_SCRIPT=true

addons:
  apt:
    packages:
    - graphviz
    
cache:
  directories:
  - "$HOME/.composer/cache"
  
before_install:
- mkdir -p ~/.composer
- composer self-update
- composer install --prefer-dist --dev
- pear channel-discover pear.phpdoc.org
- pear install phpdoc/phpDocumentor
- phpenv rehash

before_script:
- mkdir -p build/{logs,coverage,phpdoc}

script:
- composer run testCi

after_script:
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then php vendor/bin/coveralls --verbose --config;fi